### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by DelinQu** [ymq19/edu-system-serve_SpringBoot#1]
作者您好！很感谢您开发了这个教务系统，我正在做课程实验，这个项目对我的启发意义很大！:smile:
但是您的后端项目没有上传sql文件，如果方便是否可以发我一份，非常感谢！:thanks～

**Comment by ymq19** [comment]
[https://github.com/ymq19/edu-system-serve/blob/master/example_system.sql](url)
↑其实在JavaScript写的后端版本里有

**Comment by ymq19** [comment]
> 作者您好！很感谢您开发了这个教务系统，我正在做课程实验，这个项目对我的启发意义很大！😄
> 但是您的后端项目没有上传sql文件，如果方便是否可以发我一份，非常感谢！:thanks～

https://github.com/ymq19/edu-system-serve/blob/master/example_system.sql
↑其实在JavaScript写的后端版本里有

**Comment by DelinQu** [comment]
非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ymq19/edu-system-serve_SpringBoot] sql文件 (#1)





  
作者您好！很感谢您开发了这个教务系统，我正在做课程实验，这个项目对我的启发意义很大！😄
 但是您的后端项目没有上传sql文件，如果方便是否可以发我一份，非常感谢！:thanks～
  
https://github.com/ymq19/edu-system-serve/blob/master/example_system.sql
 ↑其实在JavaScript写的后端版本里有

**Comment by DelinQu** [comment]
Hi ymq19,

Join me in sharing and discovering books on Goodreads!

https://www.goodreads.com/friend/i?e=reply%2Baooji5cem2mizylkeovtq2v6v6iavevbnhhdktpk3y%40reply.github.com&invite_token=YWRmZGM1YzktY2VmZS00YzYzLWExNDYtOWY4ZDAyNWRhNWEz&n=ymq19&utm_medium=email&utm_source=invite

- DelinQu
***@***.***)

Goodreads is a community for book lovers. It's a great way to get book recommendations from your friends and others. You can keep a list of books to read and join book clubs.


_____________________________


This email was sent by request to ***@***.***
To opt-out of future invites to Goodreads please follow this link: https://www.goodreads.com/user/block_email?email_to_block=R0NhRkdPQmY2MElseE15aWljMU1CRlZzbHlCNjFoUmE3bE90clQrSGg3NUZSbW5sMkZLWStNalJpVXF0QXpnT3ZUSmQ3cnJWaFZKM2dnS2lSZ0svSmlvQWU5dmJ3bHFpMUY1OVRXUUc4R2c9LS1sNjFlbzhIaGJRcnR4ZmU2VWRLOG5nPT0%3D--fbb422b39a01f25201b34f9b5f03e88f61ddd5a9&utm_medium=email&utm_source=invite

Questions? Visit Goodreads Help: https://www.goodreads.com/help?utm_medium=email&utm_source=invite

(c) 2022 Goodreads, Inc.
188 Spear Street, Suite 250, San Francisco, CA 94105

Privacy policy:
https://www.goodreads.com/about/privacy?utm_content=_privacy&utm_medium=email&utm_source=invite
